version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: dao-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: dao-api
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
      - WS_PORT=8080
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - /app/node_modules
    command: npm start
    restart: unless-stopped

volumes:
  redis-data:
    driver: local